// frontend/nuxt3/pages/graphql.vue
<template>
  <ul>
    <li
      v-for="character of characters.data.characters.results"
      v-bind:key="character.items"
    >
      {{ character.name }}
    </li>
  </ul>
</template>

<script setup>
  const ENDPOINT = 'https://rickandmortyapi.com/graphql'

  const { data: characters } = await useFetch(ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: `{
        characters(filter: {
          type: "Human with antennae"
        }) {
          results {
            name
            id
            type
          }
        }
      }`
    })
  })
</script>

// frontend/remix/app/routes/graphql.jsx
import { useLoaderData } from "@remix-run/react"

const GET_CHARACTERS = `{
  characters {
    results {
      name
      id
    }
  }
}`

export let loader = async () => {
  const res = await fetch(
    'https://rickandmortyapi.com/graphql', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        query: GET_CHARACTERS
      })
    }
  )
  const { data }  = await res.json()
  return data.characters
}

export default function Index() {
  let { results } = useLoaderData()

  return (
    <>
      <ul>
        {results.map(({ name, id }) => (
          <li key={id}>
            {name}
          </li>
        ))}
      </ul>
    </>
  )
}
